data:
  batch_size: 64
  val_batch_size: 64
  num_workers: 6
  data_fn: "data_split/cube.{}.txt"
  data_dir: ./data/pc_data/cube/
  data_val_dir: ./data/pc_data/cube/
  mesh_data_dir: ../breaking-bad-dataset/data/
  save_pc_data_path: ./data/pc_data/cube/
  rot_range: -1
  overfit: -1
  data_keys:
    - 'part_ids'
  num_pc_points: 1000 
  min_num_part: 2
  max_num_part: 20
  shuffle_parts: False
  category: all
